version: '3'
services:
  frontend:
    build:
      context: ./internal-sales-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./internal-sales-backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
